apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset
spec:
  serviceName: "pgset"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  serviceName: "pgsql-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: backup
        image: postgres:12.15
        command:
        - "bash"
        - "-c"
        - |
          if ! hostname | grep -q 'pgset-0'; then
            until PGPASSWORD=SuperSecret pg_basebackup -h pgset-0.pgsql-headless.default.svc.cluster.local -U replicarole -p 5432 -D /var/lib/postgresql/data/pgdata -Fp -Xs -P -R -S pgset1_slot; do
              echo "Waiting for the Master database to be ready..."
              sleep 2
            done
          fi
      containers:
      - name: postgres
        image: postgres:12.15
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        lifecycle:
          postStart:
            exec:
              command: 
              - "bash"
              - "-c"
              - |
                #!/bin/bash
                set -e
                # Poll until Postgres is ready
                until pg_isready -U postgres; do
                  echo "Waiting for PostgreSQL to start..."
                  sleep 2
                done
                # If it is the first pod (master)
                if hostname | grep -q 'pgset-0'; then
                  echo "Post-start setup as Master..."
                  # Perform master specific setup
                  psql -U postgres -c "ALTER SYSTEM SET listen_addresses TO '*';"
                  psql -U postgres -c "SELECT pg_reload_conf();"
                  psql -U postgres -c "CREATE USER replicarole WITH REPLICATION ENCRYPTED PASSWORD 'SuperSecret';"
                  echo "host replication replicarole all md5" >> /var/lib/postgresql/data/pgdata/pg_hba.conf
                  sed -i "s/^#*max_wal_senders =.*$/max_wal_senders = 2/" /var/lib/postgresql/data/pgdata/postgresql.conf
                  psql -U postgres -c "SELECT pg_reload_conf();"
                  psql -U postgres -c "SELECT * FROM pg_create_physical_replication_slot('pgset1_slot');"
                else
                  echo "Post-start setup as Replica..."
                  # Perform replica specific setup
                  touch /var/lib/postgresql/data/pgdata/standby.signal
                  echo "primary_conninfo = 'user=replicarole password=SuperSecret host=pgset-0.pgsql-headless.default.svc.cluster.local port=5432 sslmode=prefer sslcompression=0 gssencmode=prefer krbsrvname=postgres target_session_attrs=any'" >> /var/lib/postgresql/data/pgdata/postgresql.auto.conf
                  echo "primary_slot_name = 'pgset1_slot'" >> /var/lib/postgresql/data/pgdata/postgresql.auto.conf
                fi
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pv-pg"
      resources:
        requests:
          storage: 1Gi
