apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset-replica
spec:
  serviceName: "pgset"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "pgsql-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.15
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        lifecycle:
          postStart:
            exec:
              command: 
              - "bash"
              - "-c"
              - |
                #!/bin/bash
                set -e
                # Poll until Postgres is ready
                until pg_isready -U postgres; do
                  echo "Waiting for PostgreSQL to start..."
                  sleep 2
                done
                echo "Post-start setup as Replica..."
                # Perform replica specific setup
                touch /var/lib/postgresql/data/pgdata/standby.signal
                echo "primary_conninfo = 'user=replicarole password=SuperSecret host=pgset-master-0.pgsql-headless.default.svc.cluster.local port=5432 sslmode=prefer sslcompression=0 gssencmode=prefer krbsrvname=postgres target_session_attrs=any'" >> /var/lib/postgresql/data/pgdata/postgresql.auto.conf
                echo "primary_slot_name = 'pgset1_slot'" >> /var/lib/postgresql/data/pgdata/postgresql.auto.conf
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pv-pg"
      resources:
        requests:
          storage: 1Gi
