apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset
spec:
  serviceName: "pgset"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  serviceName: "pgsql-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.15
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pv-pg"
      resources:
        requests:
          storage: 1Gi

