apiVersion: v1
kind: Pod
metadata:
  name: pg-backup
spec:
  containers:
  - name: pg-backup
    image: postgres:12.15
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: backup
      mountPath: /backup
  restartPolicy: OnFailure
  volumes:
  - name: backup
    persistentVolumeClaim:
      claimName: pgdata-pgset-replica-0
