apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alertmanager
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv-storage-prometheus-alertmanager-0
