apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-nodeport
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
  ports:
    - protocol: TCP
      port: 9090
      nodePort: 30090
      targetPort: 9090
  type: NodePort
