apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset-replica
spec:
  serviceName: "pgset"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "pgsql-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: init-backup
        image: postgres:12.15
        command: 
        - "bash"
        - "/spok-sts-scripts/replica-init-backup.sh"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: spok-sts-scripts
          mountPath: /spok-sts-scripts
      containers:
      - name: postgres
        image: postgres:12.15
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: spok-sts-scripts
          mountPath: /spok-sts-scripts
        lifecycle:
          postStart:
            exec:
              command: 
              - "bash"
              - "/spok-sts-scripts/replica-poststart.sh"
      volumes: # 添加这个部分
      - name: spok-sts-scripts
        configMap:
          name: spok-sts-scripts
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pv-pg"
      resources:
        requests:
          storage: 1Gi
