apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgset-master
spec:
  serviceName: "pgset"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "pgsql-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.15
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: SYNC_COMMIT  # 添加新的环境变量
            value: "true"     # 为新的环境变量设定默认值
          - name: POD_NAME  # 添加新的环境变量
            valueFrom:
              fieldRef:
                fieldPath: metadata.name  # 使用Pod的名称作为环境变量的值
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: spok-sts-scripts
          mountPath: /spok-sts-scripts
        lifecycle:
          postStart:
            exec:
              command:
              - "bash"
              - "/spok-sts-scripts/master-poststart.sh"
      volumes: # 添加这个部分
      - name: spok-sts-scripts
        configMap:
          name: spok-sts-scripts
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pv-pg"
      resources:
        requests:
          storage: 1Gi
