apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spoks.mygroup.mydomain
spec:
  group: mygroup.mydomain
  names:
    kind: Spok
    listKind: SpokList
    plural: spoks
    singular: spok
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
                default: "postgres:12.15"
              standbyReplicas:
                type: integer
                minimum: 1
                default: 1
